### ISSUE TITLE
program crash sometime

### ISSUE THREAD

**Issue by sin5678** [bfix/Tor-DNS#2]
main.process(0x1030e130, 0x76d9a260, 0x103aac20, 0x10332800, 0x800, 0x800, 0x2b)
        /home/pi/Tor-DNS/main.go:140 +0x62c
created by main.main
        /home/pi/Tor-DNS/main.go:69 +0x3d8

goroutine 97953 [IO wait]:
net.runtime_pollWait(0x76d9d340, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x6c
net.(_pollDesc).Wait(0x1032e2f8, 0x72, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x44
net.(_pollDesc).WaitRead(0x1032e2f8, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x40
net.(_netFD).Read(0x1032e2c0, 0x10354480, 0x80, 0x80, 0x0, 0x76d9a188, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:242 +0x320
net.(_conn).Read(0x1030e1c8, 0x10354480, 0x80, 0x80, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/net.go:122 +0xd4
main.answer(0x85cc, 0x0, 0x10374330, 0xa, 0x0, 0x0, 0x0, 0x1, 0x1, 0x103aace0, ...)
        /home/pi/Tor-DNS/main.go:227 +0x39c
main.process(0x1030e130, 0x76d9a260, 0x103aac60, 0x10332800, 0x800, 0x800, 0x1c)
        /home/pi/Tor-DNS/main.go:140 +0x62c
created by main.main
        /home/pi/Tor-DNS/main.go:69 +0x3d8

goroutine 97957 [IO wait]:
net.runtime_pollWait(0x76d9c560, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x6c
net.(_pollDesc).Wait(0x1032e0f8, 0x72, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x44
net.(_pollDesc).WaitRead(0x1032e0f8, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x40
net.(_netFD).Read(0x1032e0c0, 0x10354100, 0x80, 0x80, 0x0, 0x76d9a188, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:242 +0x320
net.(_conn).Read(0x1030e0d8, 0x10354100, 0x80, 0x80, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/net.go:122 +0xd4
main.answer(0xae07, 0x0, 0x103aa300, 0x19, 0x0, 0x0, 0x0, 0x1, 0x1, 0x103aa320, ...)
        /home/pi/Tor-DNS/main.go:227 +0x39c
main.process(0x1030e130, 0x76d9a260, 0x103aa0c0, 0x10332800, 0x800, 0x800, 0x2b)
        /home/pi/Tor-DNS/main.go:140 +0x62c
created by main.main
        /home/pi/Tor-DNS/main.go:69 +0x3d8

**Comment by sin5678** [comment]
seem to be a good fix. thanks a lot
